USE `timbreuse2022`;

-- Utilisateurs de test
INSERT INTO `user_sync` (`id_user`, `name`, `surname`, `date_modif`) VALUES
    (1, 'Dupont', 'Jean', '2025-01-15 08:00:00'),
    (2, 'Martin', 'Sophie', '2025-01-15 08:00:00'),
    (3, 'Müller', 'Hans', '2025-02-01 09:00:00');

-- Badges de test (associés aux utilisateurs)
-- Badge 63 : utilisé par fake_rfid.py
INSERT INTO `badge_sync` (`id_badge`, `id_user`, `rowid_badge`, `date_modif`) VALUES
    (63, 1, 1, '2025-01-15 08:00:00'),
    (589402514225, 2, 2, '2025-01-15 08:00:00'),
    (483985410385, 3, 3, '2025-02-01 09:00:00');

-- Logs de la semaine en cours (entrées/sorties réalistes)
INSERT INTO `log_sync` (`date`, `id_badge`, `inside`, `id_log`, `id_user`, `date_badge`, `date_modif`) VALUES
    (DATE_SUB(CURDATE(), INTERVAL 0 DAY) + INTERVAL 8 HOUR, 63, 1, 1, 1, DATE_SUB(CURDATE(), INTERVAL 0 DAY) + INTERVAL 8 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 8 HOUR + INTERVAL 5 MINUTE, 63, 1, 2, 1, DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 8 HOUR + INTERVAL 5 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 12 HOUR, 63, 0, 3, 1, DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 12 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 13 HOUR, 63, 1, 4, 1, DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 13 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR, 63, 0, 5, 1, DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 7 HOUR + INTERVAL 50 MINUTE, 63, 1, 6, 1, DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 7 HOUR + INTERVAL 50 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 12 HOUR + INTERVAL 10 MINUTE, 63, 0, 7, 1, DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 12 HOUR + INTERVAL 10 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 13 HOUR + INTERVAL 15 MINUTE, 63, 1, 8, 1, DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 13 HOUR + INTERVAL 15 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 17 HOUR + INTERVAL 5 MINUTE, 63, 0, 9, 1, DATE_SUB(CURDATE(), INTERVAL 2 DAY) + INTERVAL 17 HOUR + INTERVAL 5 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 3 DAY) + INTERVAL 8 HOUR + INTERVAL 10 MINUTE, 63, 1, 10, 1, DATE_SUB(CURDATE(), INTERVAL 3 DAY) + INTERVAL 8 HOUR + INTERVAL 10 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 3 DAY) + INTERVAL 16 HOUR + INTERVAL 30 MINUTE, 63, 0, 11, 1, DATE_SUB(CURDATE(), INTERVAL 3 DAY) + INTERVAL 16 HOUR + INTERVAL 30 MINUTE, NOW());

-- Logs pour l'utilisateur 2 (Sophie Martin)
INSERT INTO `log_sync` (`date`, `id_badge`, `inside`, `id_log`, `id_user`, `date_badge`, `date_modif`) VALUES
    (DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 9 HOUR, 589402514225, 1, 12, 2, DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 9 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR + INTERVAL 30 MINUTE, 589402514225, 0, 13, 2, DATE_SUB(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR + INTERVAL 30 MINUTE, NOW());

-- Logs semaine précédente (pour tester l'affichage des 2 semaines)
INSERT INTO `log_sync` (`date`, `id_badge`, `inside`, `id_log`, `id_user`, `date_badge`, `date_modif`) VALUES
    (DATE_SUB(CURDATE(), INTERVAL 8 DAY) + INTERVAL 8 HOUR, 63, 1, 14, 1, DATE_SUB(CURDATE(), INTERVAL 8 DAY) + INTERVAL 8 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 8 DAY) + INTERVAL 17 HOUR, 63, 0, 15, 1, DATE_SUB(CURDATE(), INTERVAL 8 DAY) + INTERVAL 17 HOUR, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 9 DAY) + INTERVAL 8 HOUR + INTERVAL 15 MINUTE, 63, 1, 16, 1, DATE_SUB(CURDATE(), INTERVAL 9 DAY) + INTERVAL 8 HOUR + INTERVAL 15 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 9 DAY) + INTERVAL 16 HOUR + INTERVAL 45 MINUTE, 63, 0, 17, 1, DATE_SUB(CURDATE(), INTERVAL 9 DAY) + INTERVAL 16 HOUR + INTERVAL 45 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 10 DAY) + INTERVAL 7 HOUR + INTERVAL 55 MINUTE, 63, 1, 18, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY) + INTERVAL 7 HOUR + INTERVAL 55 MINUTE, NOW()),
    (DATE_SUB(CURDATE(), INTERVAL 10 DAY) + INTERVAL 16 HOUR + INTERVAL 50 MINUTE, 63, 0, 19, 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY) + INTERVAL 16 HOUR + INTERVAL 50 MINUTE, NOW());
